### ISSUE TITLE
Unavailable http://kohanaframework.org/documentation

### ISSUE THREAD

**Issue by geekmichael** [kohana/userguide#87]
The link http://kohanaframework.org/documentation is dead (404 error), could someone fix it?

**Comment by shadowhand** [comment]
@neo22s @acoulton I don't know what you want to do about this, since the documentation requires a PHP server.

**Comment by acoulton** [comment]
I have added a basic custom 404 page to the kohanaframework.org site that points back to the homepage and gives some options for where to find docs. (gh seem to be caching their own 404 on the /documentation link but you can see it on http://kohanaframework.org/foobar

We could, I suppose, create a build task to dump the documentation out to static html files, commit them to the github pages repo and serve them as static content, but personally I think that's probably overkill.

@geekmichael unfortunately we can't reinstate the guides as-was because, as @shadowhand says they require a PHP server and now that the project has been deprecated there's no resource/funds to resource or support that. You can browse the markdown files across the module repositories, or run a local kohana server with the userguide module active and browse it there.
